# Generated by Django 3.1.2 on 2021-08-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da representada', max_length=200)),
                ('contato', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=200)),
                ('inscEstadual', models.CharField(max_length=200)),
                ('inscMunicipal', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('linha', models.CharField(max_length=200)),
                ('comissao', models.CharField(max_length=200)),
                ('ipi', models.CharField(max_length=200)),
            ],
        ),
    ]
