# Generated by Django 3.1.2 on 2021-08-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210810_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='lastUpdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='representada',
            name='lastUpdate',
            field=models.DateField(auto_now=True),
        ),
    ]
