# Generated by Django 3.1.2 on 2021-08-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210817_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='observacoes',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='representada',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
