# Generated by Django 3.1.2 on 2021-08-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210826_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistencia',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateField(),
        ),
    ]
