# Generated by Django 3.1.2 on 2021-09-16 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_assistencia_itemassistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemassistencia',
            name='assistencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.assistencia'),
        ),
    ]
