# Generated by Django 3.1.2 on 2021-09-16 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_itemassistencia_assistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='acabamento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valorParcial',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valorUnitario',
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField()),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorParcial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('acabamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.acabamento')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.pedido')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.produto')),
            ],
        ),
    ]
