# Generated by Django 3.1.2 on 2021-09-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20210915_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemassistencia',
            name='observacoes',
            field=models.CharField(max_length=200),
        ),
    ]
